#DATABASE
spring:
  datasource:
    driver-class-name : ${DB_DRIVER}
    url : ${DB_URL}
    username : ${DB_USER}
    password : ${DB_PASSWORD}

#JPA
  jpa:
    show-sql : true
    properties:
      hibernate:
        format_sql : true
       #ddl-auto : update
server:
  error:
    include-stacktrace : never